### ISSUE TITLE
COE issue with duplicate connections to multiple FMUs

### ISSUE THREAD

**Issue by richardpayne** [into-cps/INTO-CPS_Application#12]
There is an issue with the COE when there are multiple connections from the same FMU variable to multiple other FMUs. In the extract of a config below:

	"{guid}.controller.xOut":["{9737bfcb-3243-4f09-ac5c-9ac4872e3d94}.sensor1.robot_x"],
	"{guid}.controller.yOut":["{9737bfcb-3243-4f09-ac5c-9ac4872e3d94}.sensor1.robot_y"],	
	"{guid}.controller.xOut":["{09870916-25e8-4dd6-9f73-e77f5cad4edb}.sensor2.robot_x"],
	"{guid}.controller.yOut":["{09870916-25e8-4dd6-9f73-e77f5cad4edb}.sensor2.robot_y"]

There are two variables xOut and yOut that are generated in the controller FMU and are sent to both sensor1 and sensor2 FMUs.  Looking at the reported positions in the results it seems that these positions are sent to sensor 2 but not to sensor 1, i.e. the reported position of sensor 1 never changes. It seems that the variables exported by the controller FMU are only sent to the last sensor declared in the config.json.

**Comment by CThuleHansen** [comment]
I have talked to Carl Gamble concerning this issue as well.
The issue lies in the configuration. The connections object in the config.json (“connections”} takes objects consisting of: a single output and a LIST of inputs. 
So instead of:
```
"{guid}.controller.xOut":["{9737bfcb-3243-4f09-ac5c-9ac4872e3d94}.sensor1.robot_x"],
"{guid}.controller.xOut":["{09870916-25e8-4dd6-9f73-e77f5cad4edb}.sensor2.robot_x"],
```
It should be
`"{guid}.controller.xOut":["{9737bfcb-3243-4f09-ac5c-9ac4872e3d94}.sensor1.robot_x","{09870916-25e8-4dd6-9f73-e77f5cad4edb}.sensor2.robot_x"],`

**Comment by richardpayne** [comment]
Thanks Casper (I raised this on Carl's behalf). Should the COE handle this issue anyway? I can't see why it would behave in this way.

**Comment by CThuleHansen** [comment]
It is just a matter of how to configure it. I think it makes sense to define all the inputs for a given output. Otherwise you have to write the exact same output multiple times in your configuration. This seems like unnecessary code duplication and can lead to errors when updating the config and forgetting some places.

Maybe the COE should present a warning in this case.

**Comment by CThuleHansen** [comment]
I consider this closed, as it was a configuration issue.
Please reopen, if you disagree :)
